//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4439
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientCode { get; set; }
        public string FIO { get; set; }
        public System.DateTime Birthday { get; set; }
        public string ClientIndex { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int HouseNumber { get; set; }
        public int FlatNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
